/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package main;

import static java.awt.Component.CENTER_ALIGNMENT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author alfins
 */
public class IntFormMobil extends javax.swing.JInternalFrame {

    /**
     * Creates new form IntFormMobil
     */
    public IntFormMobil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        optedit = new javax.swing.JRadioButton();
        optbaru = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        txtPlat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMerk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txthargaSW = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmdsimpan = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbarang = new javax.swing.JTable();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(optedit);
        optedit.setText("Edit");
        optedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opteditMouseClicked(evt);
            }
        });
        optedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opteditActionPerformed(evt);
            }
        });

        buttonGroup1.add(optbaru);
        optbaru.setText("Baru");
        optbaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optbaruMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optbaru)
                    .addComponent(optedit))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(optbaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optedit)
                .addGap(14, 14, 14))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtPlat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlatKeyReleased(evt);
            }
        });

        jLabel2.setText("No. Plat");

        jLabel3.setText("Merk Mobil");

        jLabel4.setText("Harga Sewa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMerk)
                            .addComponent(txthargaSW)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(txtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txthargaSW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setText("Input Mobil");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmdsimpan.setText("Simpan");
        cmdsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdsimpanMouseClicked(evt);
            }
        });

        cmdhapus.setText("Hapus");
        cmdhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdhapusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(cmdsimpan)
                .addGap(72, 72, 72)
                .addComponent(cmdhapus)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsimpan)
                    .addComponent(cmdhapus))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        tblbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String koneksi="jdbc:mysql://localhost/dbpersewaan";
    String user="root";
    String pass="mypass";
    Connection connection;
    Statement statement;
    
    private void opteditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opteditMouseClicked
        if(tblbarang.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Tidak ada data untuk diedit...!!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            bersih();
        }
    }//GEN-LAST:event_opteditMouseClicked

    private void opteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opteditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opteditActionPerformed

    private void optbaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optbaruMouseClicked
        bersih();
    }//GEN-LAST:event_optbaruMouseClicked

    private void cmdsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdsimpanMouseClicked
        if (cmdsimpan.isEnabled() == false) {
            return;
        }
        try {
            String sql;
            if (optbaru.isSelected()) {
                sql = "insert into mobil values('";
                sql += txtPlat.getText() + "','";
                sql += txtMerk.getText() + "',";
                sql += txthargaSW.getText() + ")";
            } else {
                sql = "update mobil set Merk='";
                sql += txtMerk.getText() + "',hargaSW=";
                sql += txthargaSW.getText() +" ";
                sql += "where NoPlat='" + txtPlat.getText() + "'";
            }
            statement.executeUpdate (sql);
            JOptionPane.showMessageDialog(this, "Simpan / Update Data Berhasil",
                "Informasi", JOptionPane. INFORMATION_MESSAGE);
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Simpan / Update Data Gagal",
                "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error : " + DBException);
        }
        bersih();
    }//GEN-LAST:event_cmdsimpanMouseClicked

    private void cmdhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdhapusMouseClicked
        if (cmdhapus.isEnabled() == false) {
            return;
        }
        try {
            String sql = "delete from mobil where NoPlat='" + txtPlat.getText() + "'";
            statement.executeUpdate (sql);
            JOptionPane.showMessageDialog(this, "Hapus Data Berhasil",
                "Informasi", JOptionPane. INFORMATION_MESSAGE) ;
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Hapus Data Gagal",
                "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error : " + DBException);
        } bersih();
    }//GEN-LAST:event_cmdhapusMouseClicked

    private void tblbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbarangMouseClicked
        if (optedit.isSelected()) {
            txtPlat.setText (tblbarang.getValueAt (tblbarang.getSelectedRow(), 0).toString());
            txtMerk.setText (tblbarang.getValueAt (tblbarang.getSelectedRow(), 1).toString());
            txthargaSW.setText (tblbarang.getValueAt (tblbarang.getSelectedRow(), 2).toString());
            cmdhapus.setEnabled (true);
        }
    }//GEN-LAST:event_tblbarangMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            Class. forName("com.mysql.cj.jdbc.Driver"); 
            koneksi="jdbc:mysql://localhost/dbpersewaan";
            connection=DriverManager.getConnection(koneksi,user,pass);
            //statement=connection.createStatement ();
            statement=connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, 
                        ResultSet.CONCUR_UPDATABLE);
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Koneksi Gagal",
                    "Error", JOptionPane.ERROR_MESSAGE); 
                    System.err.println("Error : " + DBException);
        } 
        bersih ();
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtPlatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlatKeyReleased
        
    }//GEN-LAST:event_txtPlatKeyReleased

     private void bersih() {
        txtPlat.setText(""); 
        txtMerk.setText (""); 
        txthargaSW.setText("0"); 
        txtPlat.requestFocus(); 
        optbaru.setSelected (true); 
        optedit.setSelected (false) ; 
        cmdhapus.setEnabled (false); 
        cmdsimpan.setEnabled (true) ; 
        try{ 
            String sql="select * from mobil";
            ResultSet rs=statement.executeQuery (sql); 
            final String[] headers={"NoPlat", "Merk", "HargaSW"}; 
            rs.last();
            int n=rs.getRow();
            Object[][] data=new Object[n] [3]; 
            int p=0; 
            rs.beforeFirst(); 
            while (rs.next()){ 
                data[p][0]=rs.getString(1);
                data[p][1]=rs.getString(2); 
                data[p][2]=rs.getString (3); 
                p++;
            } 
            tblbarang.setModel(new javax.swing.table.DefaultTableModel (data, headers)); 
            tblbarang.setAlignmentX(CENTER_ALIGNMENT); 
        } catch (Exception DBException) {
            System.err.println("Error : " + DBException);
        }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JButton cmdsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton optbaru;
    private javax.swing.JRadioButton optedit;
    private javax.swing.JTable tblbarang;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtPlat;
    private javax.swing.JTextField txthargaSW;
    // End of variables declaration//GEN-END:variables
}
